name: Deploy Enso Subgraph

on: [push]

jobs:
  deploy:
    name: Deploy on EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Enso Subgraph
        uses: actions/checkout@v1
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: '18.220.98.192'
          REMOTE_USER: 'ubuntu'
          TARGET: '/home/ubuntu/enso-subgraph'
      - name: Run Enso Subgraph
        env:
          MODE: prod
          ENSONET_URL: http://testnet.enso.finance
        uses: appleboy/ssh-action@master
        with:
          envs: MODE,ENSONET_URL
          host: '18.220.98.192'
          username: 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export MODE=$MODE
            export ENSONET_URL=$ENSONET_URL

            cd /home/ubuntu/enso-subgraph
            yarn
            yarn start
