---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ensoassociation/enso-subgraph:${{ github.ref_name }}
      - name: report image
        uses: codefresh-io/codefresh-report-image@latest
        with:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_CONTAINER_REGISTRY_INTEGRATION: ensodev-dockerhub
          CF_GITHUB_TOKEN: ${{ secrets.CF_GITHUB_TOKEN }}
          CF_GIT_BRANCH: ${{ github.ref_name }}
          CF_IMAGE: ensoassociation/enso-subgraph:${{ github.ref_name }}
          CF_RUNTIME_NAME: codefresh-hosted
name: Docker Image CI
'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
